apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  selector:
    matchLabels:
      app: my-flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app
          image: charliel0721/flask-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
spec:
  type: NodePort
  selector:
    app: my-flask-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
