mongodb:
  enabled: true
  replicaCount: 3
  auth:
    enabled: false
    rootUser: root
    rootPassword: "p"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 1.5
      memory: 2Gi
    requests:
      cpu: 1.5
      memory: 1Gi

postgresql:
  enabled: true
  replication:
    synchronousCommit: "off"
    numSynchronousReplicas: 1
  auth:
    postgresPassword: "p"
    username: "my_user"
    password: "p"
    database: "my_database"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

postgresql-ha:
  enabled: true
  replicaCount: 1
  username: "root"
  password: "p"
  database: "my_database"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

mariadb:
  enabled: true
  replicas: 3
  auth:
    rootPassword: "p"
    database: my_database
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

mariadb-galera:
  enabled: true
  replicaCount: 2
  rootUser:
    user: root
    password: "p"
    forcePassword: false
  db:
    user: my_user
    password: "p"
    name: my_database
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

elastic:
  enabled: false
  version: 8.6.1
  replicas: 3
  name: ic4302

kibana:
  version: 8.6.1
  replicas: 1
  name: ic4302

prometheus-elasticsearch-exporter:
  env:
    ES_USERNAME: elastic
  extraEnvSecrets:
    ES_PASSWORD:
      secret: ic4302-es-elastic-user
      key: elastic
  es:
    uri: http://ic4302-es-http:9200
    cluster_settings: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
