mongodb:
  enabled: true
  replicas: 1
  metrics:
    serviceMonitor:
      enabled: true
postgresql-ha:
  enabled: false
mariadb-galera:
  secondary:
    replicaCount: 1
  rootUser:
    user: root
    password: "p"
    forcePassword: false
  enabled: true
elastic:
  enabled: false
  version: 8.6.1
  replicas: 1
  name: ic4302
kibana:
  version: 8.6.1
  replicas: 1
  name: ic4302
prometheus-elasticsearch-exporter:
  env:
    ES_USERNAME: elastic
  extraEnvSecrets:
    ES_PASSWORD:
      secret: ic4302-es-elastic-user
      key: elastic
  es:
    uri: http://ic4302-es-http:9200
    cluster_settings: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
